### ISSUE TITLE
ISSUE: BLUFOR HAT crate ammo mismatch

### ISSUE THREAD

**Issue by Garfield0003** [johnb432/Zeus-Additions#2]
When placing a ammo crate with at least 1 set of BLUFOR HAT, currently you get 2 CLU's, 1 3CB tube, and 1 RHS Javelin tube without rockets.
This seems mismatched, as there is effectively only a single javelin set in there, with 2 extra things.

On scaling, there will always be 2 CLU's, but the other two tubes will increase as expected. I assume this is expected behaviour.

When creating a resupply box for a single person who has the RHS javelin, the correct ammo is provided.

![image](https://user-images.githubusercontent.com/60982204/107853169-60f0f880-6e0c-11eb-845a-33c174c7704e.png)

**Comment by Garfield0003** [comment]
Additionally, if it is intended behaviour to give the launcher as well as the rocket, is there a reason why in the OPFOR HAT Crate, it only provides the rockets?

**Comment by johnb432** [comment]
> On scaling, there will always be 2 CLU's, but the other two tubes will increase as expected. I assume this is expected behaviour.

This is expected behaviour, but it's not very good overall.

When I originally made this I mistook the RHS javelin as a single fire unit, as opposed to actually being a launcher.
So I will change it to spawn in RHS javelin ammo without the launchers and to make the CLU optional. The point of this module is purely to be ammo, so no including launchers unless necessary.

**Comment by johnb432** [comment]
As this mod has been whitelisted I'm taking it that the issue has been remedied.
